version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbci-rest-client
    restart: unless-stopped
    ports:
      - "8020:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - FINTS_BANK_URL=${FINTS_BANK_URL}
      - FINTS_BANK_CODE=${FINTS_BANK_CODE}
      - FINTS_USERNAME=${FINTS_USERNAME}
      - FINTS_PIN=${FINTS_PIN}
      - API_PASSWORD=${API_PASSWORD}
